### ISSUE TITLE
Problem while compiling pydisp.pyx

### ISSUE THREAD

**Issue by r-tw-k** [xin2zhang/MCDisp#1]
While installing the package I'm facing problem with compilation of pydisp.py package and it is giving me the following error
```
Compiling pydisp/pydisp.pyx because it changed.
[1/1] Cythonizing pydisp/pydisp.pyx
/home/ritwik/.local/lib/python3.8/site-packages/Cython/Compiler/Main.py:384: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /home/ritwik/MCDisp/pydisp/pydisp.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)

Error compiling Cython file:
------------------------------------------------------------
...
        modetype : 1 for Rayleigh wave, 0 for Love wave
        phasetype: 1 for group velocity, 0 for phase velocity
        dc       : the spacing of phase velocity which is used to search phase velocities 
    '''

    npy_intp n = thick.shape[0]
             ^
------------------------------------------------------------

pydisp/pydisp.pyx:24:13: Syntax error in simple statement list
Traceback (most recent call last):
  File "setup.py", line 32, in <module>
    ext_modules=cythonize(ext_modules),
  File "/home/ritwik/.local/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1134, in cythonize
    cythonize_one(*args)
  File "/home/ritwik/.local/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1301, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: pydisp/pydisp.pyx


```

**Comment by xin2zhang** [comment]
Hi,
I have made some changes. Please try the newest version.

Best wishes,
Xin

**Comment by r-tw-k** [comment]
Downgrading the Cython version to 0.29.36 solved the issue. 
To install Cython 0.29.36 use command
```
pip install Cython==0.29.36
```
